version: 2
updates:
  # ==========================================================================
  # 1. GRADLE CONFIGURATION - MAIN BRANCH
  # ==========================================================================
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "14:25"
      timezone: "Europe/Berlin"
    
    # Specifies the GitHub usernames of individuals requested to review the created PRs
    reviewers:
      - "mastertomspirit"
      
    # Restricts the maximum number of concurrent open Pull Requests to prevent repository clutter
    open-pull-requests-limit: 5

    # Assigns specific organizational tags to the PRs for easier filtering and automated workflows
    labels:
      - "dependencies"

    # Defines rules to consolidate multiple dependency updates into single, manageable Pull Requests
    groups:
      # Combines all non-breaking updates (Minor and Patch) into a single daily PR to reduce noise
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Commit messages settings
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # ==========================================================================
  # 2. GITHUB ACTIONS CONFIGURATION
  # ==========================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    reviewers:
      - "mastertomspirit"
    labels:
      - "dependencies"
      - "github-action"
    commit-message:
      prefix: "ci"
      include: "scope"